// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.lanxing.netty.demo6;

public final class DataInfo {
  private DataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lanxing.netty.demo6.MessageType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
     */
    boolean hasDataType();
    /**
     * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
     */
    com.lanxing.netty.demo6.DataInfo.MessageType.DataType getDataType();

    /**
     * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
     */
    boolean hasStudent();
    /**
     * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
     */
    com.lanxing.netty.demo6.DataInfo.Student getStudent();
    /**
     * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
     */
    com.lanxing.netty.demo6.DataInfo.StudentOrBuilder getStudentOrBuilder();

    /**
     * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
     */
    boolean hasCourse();
    /**
     * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
     */
    com.lanxing.netty.demo6.DataInfo.Course getCourse();
    /**
     * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
     */
    com.lanxing.netty.demo6.DataInfo.CourseOrBuilder getCourseOrBuilder();

    public com.lanxing.netty.demo6.DataInfo.MessageType.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code com.lanxing.netty.demo6.MessageType}
   */
  public  static final class MessageType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lanxing.netty.demo6.MessageType)
      MessageTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageType.newBuilder() to construct.
    private MessageType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageType() {
      dataType_ = 1;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageType();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.lanxing.netty.demo6.DataInfo.MessageType.DataType value = com.lanxing.netty.demo6.DataInfo.MessageType.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.lanxing.netty.demo6.DataInfo.Student.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((com.lanxing.netty.demo6.DataInfo.Student) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.lanxing.netty.demo6.DataInfo.Student.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.lanxing.netty.demo6.DataInfo.Student) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              com.lanxing.netty.demo6.DataInfo.Course.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((com.lanxing.netty.demo6.DataInfo.Course) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(com.lanxing.netty.demo6.DataInfo.Course.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.lanxing.netty.demo6.DataInfo.Course) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_lanxing_netty_demo6_MessageType_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_lanxing_netty_demo6_MessageType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lanxing.netty.demo6.DataInfo.MessageType.class, com.lanxing.netty.demo6.DataInfo.MessageType.Builder.class);
    }

    /**
     * Protobuf enum {@code com.lanxing.netty.demo6.MessageType.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>student_type = 1;</code>
       */
      student_type(1),
      /**
       * <code>course_type = 2;</code>
       */
      course_type(2),
      ;

      /**
       * <code>student_type = 1;</code>
       */
      public static final int student_type_VALUE = 1;
      /**
       * <code>course_type = 2;</code>
       */
      public static final int course_type_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 1: return student_type;
          case 2: return course_type;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.lanxing.netty.demo6.DataInfo.MessageType.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.lanxing.netty.demo6.MessageType.DataType)
    }

    private int bitField0_;
    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      STUDENT(2),
      COURSE(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return STUDENT;
          case 3: return COURSE;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
     */
    public com.lanxing.netty.demo6.DataInfo.MessageType.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.lanxing.netty.demo6.DataInfo.MessageType.DataType result = com.lanxing.netty.demo6.DataInfo.MessageType.DataType.valueOf(dataType_);
      return result == null ? com.lanxing.netty.demo6.DataInfo.MessageType.DataType.student_type : result;
    }

    public static final int STUDENT_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
     */
    public boolean hasStudent() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
     */
    public com.lanxing.netty.demo6.DataInfo.Student getStudent() {
      if (dataBodyCase_ == 2) {
         return (com.lanxing.netty.demo6.DataInfo.Student) dataBody_;
      }
      return com.lanxing.netty.demo6.DataInfo.Student.getDefaultInstance();
    }
    /**
     * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
     */
    public com.lanxing.netty.demo6.DataInfo.StudentOrBuilder getStudentOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (com.lanxing.netty.demo6.DataInfo.Student) dataBody_;
      }
      return com.lanxing.netty.demo6.DataInfo.Student.getDefaultInstance();
    }

    public static final int COURSE_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
     */
    public boolean hasCourse() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
     */
    public com.lanxing.netty.demo6.DataInfo.Course getCourse() {
      if (dataBodyCase_ == 3) {
         return (com.lanxing.netty.demo6.DataInfo.Course) dataBody_;
      }
      return com.lanxing.netty.demo6.DataInfo.Course.getDefaultInstance();
    }
    /**
     * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
     */
    public com.lanxing.netty.demo6.DataInfo.CourseOrBuilder getCourseOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (com.lanxing.netty.demo6.DataInfo.Course) dataBody_;
      }
      return com.lanxing.netty.demo6.DataInfo.Course.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (com.lanxing.netty.demo6.DataInfo.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (com.lanxing.netty.demo6.DataInfo.Course) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.lanxing.netty.demo6.DataInfo.Student) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.lanxing.netty.demo6.DataInfo.Course) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lanxing.netty.demo6.DataInfo.MessageType)) {
        return super.equals(obj);
      }
      com.lanxing.netty.demo6.DataInfo.MessageType other = (com.lanxing.netty.demo6.DataInfo.MessageType) obj;

      if (hasDataType() != other.hasDataType()) return false;
      if (hasDataType()) {
        if (dataType_ != other.dataType_) return false;
      }
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getStudent()
              .equals(other.getStudent())) return false;
          break;
        case 3:
          if (!getCourse()
              .equals(other.getCourse())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + COURSE_FIELD_NUMBER;
          hash = (53 * hash) + getCourse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.MessageType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lanxing.netty.demo6.DataInfo.MessageType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lanxing.netty.demo6.MessageType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lanxing.netty.demo6.MessageType)
        com.lanxing.netty.demo6.DataInfo.MessageTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_lanxing_netty_demo6_MessageType_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_lanxing_netty_demo6_MessageType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lanxing.netty.demo6.DataInfo.MessageType.class, com.lanxing.netty.demo6.DataInfo.MessageType.Builder.class);
      }

      // Construct using com.lanxing.netty.demo6.DataInfo.MessageType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_lanxing_netty_demo6_MessageType_descriptor;
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.MessageType getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.MessageType build() {
        com.lanxing.netty.demo6.DataInfo.MessageType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.MessageType buildPartial() {
        com.lanxing.netty.demo6.DataInfo.MessageType result = new com.lanxing.netty.demo6.DataInfo.MessageType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (studentBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = studentBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (courseBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = courseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lanxing.netty.demo6.DataInfo.MessageType) {
          return mergeFrom((com.lanxing.netty.demo6.DataInfo.MessageType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lanxing.netty.demo6.DataInfo.MessageType other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        switch (other.getDataBodyCase()) {
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case COURSE: {
            mergeCourse(other.getCourse());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasDataType()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lanxing.netty.demo6.DataInfo.MessageType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lanxing.netty.demo6.DataInfo.MessageType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dataType_ = 1;
      /**
       * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
       */
      public com.lanxing.netty.demo6.DataInfo.MessageType.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.lanxing.netty.demo6.DataInfo.MessageType.DataType result = com.lanxing.netty.demo6.DataInfo.MessageType.DataType.valueOf(dataType_);
        return result == null ? com.lanxing.netty.demo6.DataInfo.MessageType.DataType.student_type : result;
      }
      /**
       * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
       */
      public Builder setDataType(com.lanxing.netty.demo6.DataInfo.MessageType.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.lanxing.netty.demo6.MessageType.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.lanxing.netty.demo6.DataInfo.Student, com.lanxing.netty.demo6.DataInfo.Student.Builder, com.lanxing.netty.demo6.DataInfo.StudentOrBuilder> studentBuilder_;
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public boolean hasStudent() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public com.lanxing.netty.demo6.DataInfo.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (com.lanxing.netty.demo6.DataInfo.Student) dataBody_;
          }
          return com.lanxing.netty.demo6.DataInfo.Student.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return studentBuilder_.getMessage();
          }
          return com.lanxing.netty.demo6.DataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public Builder setStudent(com.lanxing.netty.demo6.DataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public Builder setStudent(
          com.lanxing.netty.demo6.DataInfo.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public Builder mergeStudent(com.lanxing.netty.demo6.DataInfo.Student value) {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != com.lanxing.netty.demo6.DataInfo.Student.getDefaultInstance()) {
            dataBody_ = com.lanxing.netty.demo6.DataInfo.Student.newBuilder((com.lanxing.netty.demo6.DataInfo.Student) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public com.lanxing.netty.demo6.DataInfo.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      public com.lanxing.netty.demo6.DataInfo.StudentOrBuilder getStudentOrBuilder() {
        if ((dataBodyCase_ == 2) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (com.lanxing.netty.demo6.DataInfo.Student) dataBody_;
          }
          return com.lanxing.netty.demo6.DataInfo.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Student student = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lanxing.netty.demo6.DataInfo.Student, com.lanxing.netty.demo6.DataInfo.Student.Builder, com.lanxing.netty.demo6.DataInfo.StudentOrBuilder>
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = com.lanxing.netty.demo6.DataInfo.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lanxing.netty.demo6.DataInfo.Student, com.lanxing.netty.demo6.DataInfo.Student.Builder, com.lanxing.netty.demo6.DataInfo.StudentOrBuilder>(
                  (com.lanxing.netty.demo6.DataInfo.Student) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.lanxing.netty.demo6.DataInfo.Course, com.lanxing.netty.demo6.DataInfo.Course.Builder, com.lanxing.netty.demo6.DataInfo.CourseOrBuilder> courseBuilder_;
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public boolean hasCourse() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public com.lanxing.netty.demo6.DataInfo.Course getCourse() {
        if (courseBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (com.lanxing.netty.demo6.DataInfo.Course) dataBody_;
          }
          return com.lanxing.netty.demo6.DataInfo.Course.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return courseBuilder_.getMessage();
          }
          return com.lanxing.netty.demo6.DataInfo.Course.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public Builder setCourse(com.lanxing.netty.demo6.DataInfo.Course value) {
        if (courseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          courseBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public Builder setCourse(
          com.lanxing.netty.demo6.DataInfo.Course.Builder builderForValue) {
        if (courseBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          courseBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public Builder mergeCourse(com.lanxing.netty.demo6.DataInfo.Course value) {
        if (courseBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != com.lanxing.netty.demo6.DataInfo.Course.getDefaultInstance()) {
            dataBody_ = com.lanxing.netty.demo6.DataInfo.Course.newBuilder((com.lanxing.netty.demo6.DataInfo.Course) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            courseBuilder_.mergeFrom(value);
          }
          courseBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public Builder clearCourse() {
        if (courseBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          courseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public com.lanxing.netty.demo6.DataInfo.Course.Builder getCourseBuilder() {
        return getCourseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      public com.lanxing.netty.demo6.DataInfo.CourseOrBuilder getCourseOrBuilder() {
        if ((dataBodyCase_ == 3) && (courseBuilder_ != null)) {
          return courseBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (com.lanxing.netty.demo6.DataInfo.Course) dataBody_;
          }
          return com.lanxing.netty.demo6.DataInfo.Course.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.lanxing.netty.demo6.Course course = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.lanxing.netty.demo6.DataInfo.Course, com.lanxing.netty.demo6.DataInfo.Course.Builder, com.lanxing.netty.demo6.DataInfo.CourseOrBuilder>
          getCourseFieldBuilder() {
        if (courseBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = com.lanxing.netty.demo6.DataInfo.Course.getDefaultInstance();
          }
          courseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.lanxing.netty.demo6.DataInfo.Course, com.lanxing.netty.demo6.DataInfo.Course.Builder, com.lanxing.netty.demo6.DataInfo.CourseOrBuilder>(
                  (com.lanxing.netty.demo6.DataInfo.Course) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return courseBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lanxing.netty.demo6.MessageType)
    }

    // @@protoc_insertion_point(class_scope:com.lanxing.netty.demo6.MessageType)
    private static final com.lanxing.netty.demo6.DataInfo.MessageType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lanxing.netty.demo6.DataInfo.MessageType();
    }

    public static com.lanxing.netty.demo6.DataInfo.MessageType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MessageType>
        PARSER = new com.google.protobuf.AbstractParser<MessageType>() {
      @Override
      public MessageType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageType> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageType> getParserForType() {
      return PARSER;
    }

    @Override
    public com.lanxing.netty.demo6.DataInfo.MessageType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lanxing.netty.demo6.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>optional string address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    String getAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.lanxing.netty.demo6.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lanxing.netty.demo6.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_lanxing_netty_demo6_Student_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_lanxing_netty_demo6_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lanxing.netty.demo6.DataInfo.Student.class, com.lanxing.netty.demo6.DataInfo.Student.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile Object address_;
    /**
     * <code>optional string address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lanxing.netty.demo6.DataInfo.Student)) {
        return super.equals(obj);
      }
      com.lanxing.netty.demo6.DataInfo.Student other = (com.lanxing.netty.demo6.DataInfo.Student) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lanxing.netty.demo6.DataInfo.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lanxing.netty.demo6.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lanxing.netty.demo6.Student)
        com.lanxing.netty.demo6.DataInfo.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_lanxing_netty_demo6_Student_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_lanxing_netty_demo6_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lanxing.netty.demo6.DataInfo.Student.class, com.lanxing.netty.demo6.DataInfo.Student.Builder.class);
      }

      // Construct using com.lanxing.netty.demo6.DataInfo.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_lanxing_netty_demo6_Student_descriptor;
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.Student getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.Student build() {
        com.lanxing.netty.demo6.DataInfo.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.Student buildPartial() {
        com.lanxing.netty.demo6.DataInfo.Student result = new com.lanxing.netty.demo6.DataInfo.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lanxing.netty.demo6.DataInfo.Student) {
          return mergeFrom((com.lanxing.netty.demo6.DataInfo.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lanxing.netty.demo6.DataInfo.Student other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lanxing.netty.demo6.DataInfo.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lanxing.netty.demo6.DataInfo.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lanxing.netty.demo6.Student)
    }

    // @@protoc_insertion_point(class_scope:com.lanxing.netty.demo6.Student)
    private static final com.lanxing.netty.demo6.DataInfo.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lanxing.netty.demo6.DataInfo.Student();
    }

    public static com.lanxing.netty.demo6.DataInfo.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @Override
    public com.lanxing.netty.demo6.DataInfo.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CourseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.lanxing.netty.demo6.Course)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string course_name = 1;</code>
     */
    boolean hasCourseName();
    /**
     * <code>optional string course_name = 1;</code>
     */
    String getCourseName();
    /**
     * <code>optional string course_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getCourseNameBytes();
  }
  /**
   * Protobuf type {@code com.lanxing.netty.demo6.Course}
   */
  public  static final class Course extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.lanxing.netty.demo6.Course)
      CourseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Course.newBuilder() to construct.
    private Course(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Course() {
      courseName_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Course();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Course(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              courseName_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_lanxing_netty_demo6_Course_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_lanxing_netty_demo6_Course_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lanxing.netty.demo6.DataInfo.Course.class, com.lanxing.netty.demo6.DataInfo.Course.Builder.class);
    }

    private int bitField0_;
    public static final int COURSE_NAME_FIELD_NUMBER = 1;
    private volatile Object courseName_;
    /**
     * <code>optional string course_name = 1;</code>
     */
    public boolean hasCourseName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string course_name = 1;</code>
     */
    public String getCourseName() {
      Object ref = courseName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          courseName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string course_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCourseNameBytes() {
      Object ref = courseName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        courseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, courseName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, courseName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.lanxing.netty.demo6.DataInfo.Course)) {
        return super.equals(obj);
      }
      com.lanxing.netty.demo6.DataInfo.Course other = (com.lanxing.netty.demo6.DataInfo.Course) obj;

      if (hasCourseName() != other.hasCourseName()) return false;
      if (hasCourseName()) {
        if (!getCourseName()
            .equals(other.getCourseName())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCourseName()) {
        hash = (37 * hash) + COURSE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getCourseName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.lanxing.netty.demo6.DataInfo.Course parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.lanxing.netty.demo6.DataInfo.Course prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.lanxing.netty.demo6.Course}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.lanxing.netty.demo6.Course)
        com.lanxing.netty.demo6.DataInfo.CourseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_lanxing_netty_demo6_Course_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_lanxing_netty_demo6_Course_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lanxing.netty.demo6.DataInfo.Course.class, com.lanxing.netty.demo6.DataInfo.Course.Builder.class);
      }

      // Construct using com.lanxing.netty.demo6.DataInfo.Course.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        courseName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_lanxing_netty_demo6_Course_descriptor;
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.Course getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.Course build() {
        com.lanxing.netty.demo6.DataInfo.Course result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.lanxing.netty.demo6.DataInfo.Course buildPartial() {
        com.lanxing.netty.demo6.DataInfo.Course result = new com.lanxing.netty.demo6.DataInfo.Course(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.courseName_ = courseName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lanxing.netty.demo6.DataInfo.Course) {
          return mergeFrom((com.lanxing.netty.demo6.DataInfo.Course)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lanxing.netty.demo6.DataInfo.Course other) {
        if (other == getDefaultInstance()) return this;
        if (other.hasCourseName()) {
          bitField0_ |= 0x00000001;
          courseName_ = other.courseName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lanxing.netty.demo6.DataInfo.Course parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lanxing.netty.demo6.DataInfo.Course) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object courseName_ = "";
      /**
       * <code>optional string course_name = 1;</code>
       */
      public boolean hasCourseName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string course_name = 1;</code>
       */
      public String getCourseName() {
        Object ref = courseName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            courseName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string course_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCourseNameBytes() {
        Object ref = courseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          courseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string course_name = 1;</code>
       */
      public Builder setCourseName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        courseName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string course_name = 1;</code>
       */
      public Builder clearCourseName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        courseName_ = getDefaultInstance().getCourseName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string course_name = 1;</code>
       */
      public Builder setCourseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        courseName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.lanxing.netty.demo6.Course)
    }

    // @@protoc_insertion_point(class_scope:com.lanxing.netty.demo6.Course)
    private static final com.lanxing.netty.demo6.DataInfo.Course DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.lanxing.netty.demo6.DataInfo.Course();
    }

    public static com.lanxing.netty.demo6.DataInfo.Course getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Course>
        PARSER = new com.google.protobuf.AbstractParser<Course>() {
      @Override
      public Course parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Course(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Course> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Course> getParserForType() {
      return PARSER;
    }

    @Override
    public com.lanxing.netty.demo6.DataInfo.Course getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanxing_netty_demo6_MessageType_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanxing_netty_demo6_MessageType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanxing_netty_demo6_Student_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanxing_netty_demo6_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanxing_netty_demo6_Course_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanxing_netty_demo6_Course_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rstudent.proto\022\027com.lanxing.netty.demo6" +
      "\"\363\001\n\013MessageType\022@\n\tdata_type\030\001 \002(\0162-.co" +
      "m.lanxing.netty.demo6.MessageType.DataTy" +
      "pe\0223\n\007student\030\002 \001(\0132 .com.lanxing.netty." +
      "demo6.StudentH\000\0221\n\006course\030\003 \001(\0132\037.com.la" +
      "nxing.netty.demo6.CourseH\000\"-\n\010DataType\022\020" +
      "\n\014student_type\020\001\022\017\n\013course_type\020\002B\013\n\tdat" +
      "a_body\"5\n\007Student\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002" +
      " \001(\005\022\017\n\007address\030\003 \001(\t\"\035\n\006Course\022\023\n\013cours" +
      "e_name\030\001 \001(\tB%\n\027com.lanxing.netty.demo6B" +
      "\010DataInfoH\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_lanxing_netty_demo6_MessageType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lanxing_netty_demo6_MessageType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanxing_netty_demo6_MessageType_descriptor,
        new String[] { "DataType", "Student", "Course", "DataBody", });
    internal_static_com_lanxing_netty_demo6_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lanxing_netty_demo6_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanxing_netty_demo6_Student_descriptor,
        new String[] { "Name", "Age", "Address", });
    internal_static_com_lanxing_netty_demo6_Course_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lanxing_netty_demo6_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanxing_netty_demo6_Course_descriptor,
        new String[] { "CourseName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
